language: ruby
before_install:
  - yes | gem update --system --force
  - gem install bundler
script: bundle exec rspec
rvm:
  - 2.3.0
  - 2.6.5
notifications:
  email:
    recipients:
      - dev@retailcommon.com
    on_success: change
    on_failure: always
