language: ruby
before_install: gem update --system
script: bundle exec rspec
rvm:
- 2.6.0
notifications:
  email:
    recipients:
      - dev@retailcommon.com
    on_success: change
    on_failure: always
